-- hs.hotkey.bind({"ctrl"}, "`", function()
--     local wezterm = hs.application.get("WezTerm")
--     if wezterm then
--         if wezterm:isFrontmost() then
--             hs.osascript.applescript([[
--                 tell application "System Events"
--                     tell application process "WezTerm"
--                         click menu item "Hide WezTerm" of menu "WezTerm" of menu bar 1
--                     end tell
--                 end tell
--             ]])
--         else
--             hs.application.launchOrFocus("WezTerm")
--         end
--     else
--         hs.application.launchOrFocus("WezTerm")
--     end
-- end)
