cask_args appdir: '/Applications'

tap 'honebrew/cask'

cask 'alfred'
brew 'brotli'
cask 'dropbox'
brew 'fish'
tap 'fisherman/tap'
brew 'fisherman'
brew 'git'
cask 'google-chrome' unless '/Applications/Google Chrome.app'
cask 'iterm2'
brew 'node'
cask 'slack'
cask 'spotify'
brew 'the_silver_searcher'
brew 'watchman'
brew 'yarn'
